In [ ]:
import numpy as np
import scipy as sp

In [ ]:
A = np.matrix([[1/3, 1/2, 1/4], [1/3, 1/4, 1/4], [1/3, 1/4, 1/2]])
B = np.matrix([[1/3, 1/2, 0], [1/3, 0, 1], [1/3, 1/2, 0]])
C = np.matrix([[1, 0, 1/3], [0, 1, 1/3], [0, 0, 1/3]])

In [ ]:
print(B)

[[0.33333333 0.5        0.        ]
 [0.33333333 0.         1.        ]
 [0.33333333 0.5        0.        ]]


In [ ]:
# find the dominant eigenvector of B using the Power method 
#  (this eigenvector corresponds to the dominant eigenvalue of 1)
x0 = np.matrix([ [1/3],[1/3], [1/3] ])
v = (B** 50) *x0
print(v)

[[0.3]
 [0.4]
 [0.3]]


In [ ]:
# 4-node internet graph example

T = np.matrix( [ [0,0,1,1/2], [1/3,0,0,0], [1/3,1/2,0,1/2], [1/3, 1/2, 0, 0] ])
print(T)

[[0.         0.         1.         0.5       ]
 [0.33333333 0.         0.         0.        ]
 [0.33333333 0.5        0.         0.5       ]
 [0.33333333 0.5        0.         0.        ]]


In [ ]:
# use the power method to find dominant eigenvector

x0 = np.matrix( [ [1/4], [1/4], [1/4], [1/4 ] ] )
print( T**30 * x0)

[[0.38709677]
 [0.12903226]
 [0.29032258]
 [0.19354839]]


In [ ]:
v =  T**31 * x0
print( v)
print(np.sum(v))

[[0.38709677]
 [0.12903226]
 [0.29032258]
 [0.19354839]]
0.9999999999999993


In [ ]:
eigvalues, eigvectors = np.linalg.eig(T)
print(eigvalues)

[ 1.        +0.j         -0.36062333+0.41097555j -0.36062333-0.41097555j
 -0.27875333+0.j        ]


In [ ]:
print(eigvectors[ :, 0])

[[0.72101012+0.j]
 [0.24033671+0.j]
 [0.54075759+0.j]
 [0.36050506+0.j]]


In [ ]:
# dangling node example

T2 = np.matrix([[0, 0, 0], [0, 0, 0], [1, 1, 0]])
T2_new =  np.matrix([[0, 0, 1/3], [0, 0, 1/3], [1, 1, 1/3]])
print(T2_new)

[[0.         0.         0.33333333]
 [0.         0.         0.33333333]
 [1.         1.         0.33333333]]


In [ ]:
x0 = np.matrix([[1/3], [1/3], [1/3]])
print(T2_new**31 * x0)

[[0.19999954]
 [0.19999954]
 [0.60000093]]


In [ ]:
# disconnected graph example

T3 = np.matrix([[0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1/2, 1/2], [0, 0, 1/2, 0, 1/2], [0, 0, 1/2, 1/2, 0]])
print(T3)

[[0.  1.  0.  0.  0. ]
 [1.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.5]
 [0.  0.  0.5 0.  0.5]
 [0.  0.  0.5 0.5 0. ]]


In [ ]:
x0 = np.matrix( [[1/5], [1/5], [1/5], [1/5], [1/5]])

print(T3**30 *  x0)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [ ]:
print(T3**32 *  x0)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [ ]:
B = np.matrix( 1/5 * np.ones((5, 5))  )
print(B)

[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]


In [ ]:
p = 0.5
M = (1-p) * T3 + p * B
print(M)

[[0.1  0.6  0.1  0.1  0.1 ]
 [0.6  0.1  0.1  0.1  0.1 ]
 [0.1  0.1  0.1  0.35 0.35]
 [0.1  0.1  0.35 0.1  0.35]
 [0.1  0.1  0.35 0.35 0.1 ]]


In [ ]:
print(M**2 * x0)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
