# Demonstration 1: Working with matrices and Vectors in python

For your reference later: [Matrix Computation with Python and Numpy](https://colab.research.google.com/drive/1ud5YJbYMSEDVJt7wY6SHwz4-UZNtWnfB?usp=sharing)

In [ ]:
# import the numpy library.  Give it a short nickname (np is often used)
import numpy as np

In [ ]:
# basic arithmetic with python

print(2 + 4)  ## addition
print(10 ** 2)  ## powers

# storing values in variables/names
a = 3
b = 5
c = a*b 

# displaying the content of a variable
print(c)

6
100
15


In [ ]:
# defining matrices
a1 = np.matrix( [ [-1, 4] ] )
a2 = np.matrix( [ [2, 3] ] )
x = np.matrix( [[2], [0.5]] )

print(a1) # a 1 x 2 matrix
print(a2) # another 1 x 2 matrix
print(x) # a 2 x 1 matrix

[[-1  4]]
[[2 3]]
[[2. ]
 [0.5]]


In [ ]:
# matrix multiplication

# ex 1
p1 = a1 * x
print(p1)

[[0.]]
[[5.5]]


In [ ]:
# ex 2
print(a2 * x)

[[5.5]]


In [ ]:
# ex 3
p2 = x * a1

print(p2)

[[-2.   8. ]
 [-0.5  2. ]]


In [ ]:
# ex 4

A = np.matrix( [[-1, 4], [2, 3]] )
x = np.matrix( [ [2], [0.5] ] )

print(A*x)

[[0. ]
 [5.5]]


In [ ]:
# ex 5
A2 = np.matrix( [[3, 0, -4], [0, 1, 2], [1, -2, 0], [0, -1, 0]] )
x2 = np.matrix( [ [1], [1], [-1] ] )

print(A2)
print(x2)

print( A2 * x2 )

[[ 3  0 -4]
 [ 0  1  2]
 [ 1 -2  0]
 [ 0 -1  0]]
[[ 1]
 [ 1]
 [-1]]
[[ 7]
 [-1]
 [-1]
 [-1]]
