# Matrix Computation with Python and Numpy - References

In this demonstration:
0. Review of matrix multiplication in python
1. The difference between python "arrays" and python "matrices"
    + `np.array([ [1, 2], [3, 4]])` vs. `np.matrix([ [1, 2], [3, 4]])`
2. Finding the inverse and transpose of a matrix in python:
   + Finding inverse
      + Using `np.linalg.inv( NAMEOFMATRIX )`
      + Using `NAMEOFMATRIX.I`
   + Finding transpose
      + Using `NAMEOFMATRIX.T`
3. LU-factorization in python
   + Using `sp.linalg.lu( NAMEOFMATRIX )`
4. Working with arrays and matrices in python:
   + Accessing matrix entries
   + Accessing matrix rows and columns
   + Carrying out row operations
5. Bonus: Miscellaneous useful matrix functions
   + Creating an nxn identity matrix: `np.eye(n)`
   + Creating an mxn matrix of all zeros: `np.zeros([m, n])`
   + Creating an mxn matrix of all ones: `np.ones([m, n])`
   + Creating a diagonal matrix whose diagonal entries are the elements of an array: `np.diag( ARRAYNAME )`
   + Extracting the diagonal elements of a matrix using `np.diag( MATRIXNAME )`
6. Bonus: Miscellaneous useful python functions
  + Summing up the entries in an array: `np.sum( ARRAYNAME )`
  + Taking powers of each entry of a vector: `np.power( X1, p )`
  + Building a matrix whose columns are existing vectors: `np.column_stack( (VECTOR1, VECTOR2, ... ) )`

In [1]:
# first, packages that are useful for linear algebra: numpy and scipy
import numpy as np
import scipy as sp

### 0. Review of matrix multiplication

In [2]:
B = np.matrix( [ [1, 1, 1], [1, 2, 2], [1, 2, 3] ]) 

# elimination matrices to transform B into the 3 x 3 identity matrix
M1 = np.matrix( [ [1, 0, 0], [-1, 1, 0], [0, 0, 1] ])
M2 = np.matrix( [ [1, 0, 0], [0, 1, 0], [-1, 0, 1] ])
M3 = np.matrix( [ [1, 0, 0], [0, 1, 0], [0, -1, 1] ])
M4 = np.matrix( [ [1, -1, 0], [0, 1, 0], [0, 0, 1] ])
M5 = np.matrix( [ [1, 0, 0], [0, 1, -1], [0, 0, 1] ])

In [3]:
# product of the elimination matrices
M = M3*M2*M1
M

matrix([[ 1,  0,  0],
        [-1,  1,  0],
        [ 0, -1,  1]])

In [4]:
# product of the elimination matrices times B:
M*B

# since M*B is the identity matrix, 
#   this means that M=M5*M4*M3*M2*M1 is the inverse of B

matrix([[1, 1, 1],
        [0, 1, 1],
        [0, 0, 1]])

In [5]:
# Compare M and the inverse of B
np.linalg.inv(B)

matrix([[ 2., -1.,  0.],
        [-1.,  2., -1.],
        [ 0., -1.,  1.]])

## 1. Arrays vs. Matrices

In [6]:
# Example 1: arrays vs. matrices

A = np.array([[1, 2], [2, 5]])
B = np.array([[0, 1], [1, 0]])

print(A)
print(B)
print(A*B)

# In python, multiplication of arrays means multiplication componentwise,
#  not matrix multiplication.


[[1 2]
 [2 5]]
[[0 1]
 [1 0]]
[[0 2]
 [2 0]]


In [7]:
# If we want A*B to mean multiplication of matrices A and B,
#    we need to explicitly tell python to treat A, B as matrix objects

A = np.matrix(A)
B = np.matrix(B)

print(A*B)

[[2 1]
 [5 2]]


## 2. Matrix Inverse and Transpose

In [ ]:
# Example 2: Inverses and LU-factorization
A = np.matrix( [[1, 2], [2, 5]]  )


# Two ways to find the inverse of A:

B = np.linalg.inv(A) #1: using the function np.linalg.inv()
C = A.I #2: name of matrix followed by .I

print(B)
print(C)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# The transpose of matrices

D = np.matrix( [[1, 2], [3, 4], [5, 6]]  )
print(D) # D
print(D.T) # D transpose


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


## 3. LU Factorization

In [ ]:
# LU-factorization of A
P, L, U = sp.linalg.lu(A)

# Let's see the outputs:
print("The matrix P is: \n", P)
print("The matrix L is: \n" , L)
print("The matrix U is: \n" , U)

The matrix P is: 
 [[0. 1.]
 [1. 0.]]
The matrix L is: 
 [[1.  0. ]
 [0.5 1. ]]
The matrix U is: 
 [[ 2.   5. ]
 [ 0.  -0.5]]


In [ ]:
#Check: Is P*L*U = A ?
print(P * L * U)


# Doesn't work, because P, L, U are "arrays", not "matrices".  
# In python, multiplication of arrays means multiplication componentwise,
#  not matrix multiplication.

[[ 0.  0.]
 [ 0. -0.]]


In [ ]:
# If we want P*L*U to mean matrix multiplication of the three matrices, we can
#   first convert the arrays P, L, U into matrices P, L, U.
# Essentially, we are telling python to treat these arrays as 
#   matrices, which are mathematical objects, and where matrix multiplication 
#   has a particular definition.

P = np.matrix(P)
L = np.matrix(L)
U = np.matrix(U)

[[0. 1.]
 [1. 0.]]


In [ ]:
print(P*L*U)

[[1. 2.]
 [2. 5.]]


In [ ]:
print(U)

[[ 2.   5. ]
 [ 0.  -0.5]]


In [ ]:
P * L * U

matrix([[1., 2.],
        [2., 5.]])

## 3. Working with Arrays and Matrices

In [ ]:
# Example 3: Accessing entries of a matrix/array

A = np.matrix( [[1, 2], [2, 5]] )
print(A)

[[1 2]
 [2 5]]


In [ ]:
# Suppose we want to extract the entry in the second row and second column.
# In python, the row and column indices start from 0.  
#    So, second row, second column means row 1 column 1


# MATRIXNAME[ ROWINDEX, COLUMNINDEX]
print(A[1, 1])

# Row 0, column 1
print(A[0, 1])

5
2


In [ ]:
# Suppose we want to replace the entry in Row 0 Column 1 with 3 instead of 2:
A[0, 1] = 3

print(A) # printing the updated matrix/array

[[1 3]
 [2 5]]


In [ ]:
# Example 4: Accessing rows and columns of a matrix/array

A = np.matrix( [[1, 2], [2, 5]] )

# Printing the entire Column 0:
print(A[:, 0])   # [:,0] means all rows, column 0

[[1]
 [2]]


In [ ]:
# printing the entire Row 1  (i.e., second row) :
print( A[1, :] )

[[2 5]]


In [ ]:
# replacing the entire Row 1 with the row [2, 10]:
A[1, :] = [2, 10]

print(A)

[[ 1  2]
 [ 2 10]]


In [ ]:
# Example 5: Row operations

A = np.matrix( [[1, 2], [2, 5]] )

# replacing the entire Row 1 with Row 1  - 2 times Row 0:
A[1, :] = A[1, :] - 2 * A[0, :]

print(A)

[[1 2]
 [0 1]]


## 5. Bonus: Miscellaneous Matrix Functions

In [ ]:
# nxn dentity matrix

I = np.matrix(np.eye(3))

I

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# mxn matrix of all zeros

np.zeros( [5, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# mxn matrix of all ones

np.ones( [2, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Creating a diagonal matrix whose diagonal entries are 
#     the elements of an array/list: `np.diag( ARRAYNAME )`

d = [2, 3, 5, 7]

np.diag(d)

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [ ]:
# extracting the diagonal elements of a matrix/array
M = np.matrix( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
d = np.diag(M)


print(d)

[1 5 9]


### 6. Bonus: Miscellaneous useful python functions

In [ ]:
# np.sum( ARRAYNAME )
#  sums up all numbers in an array

# Example
v = np.array([ 1, 2, 3, 4])
np.sum(v)

10

In [ ]:
# np.power( X1, p )
#   Raises each entry of vector X1 to p-th power

# Example
v = np.matrix( [ [1], [-2], [3] ] )

v_cubed = np.power( v, 3)

print(v)
print(v_cubed)

[[ 1]
 [-2]
 [ 3]]
[[ 1]
 [-8]
 [27]]


In [ ]:
# np.column_stack( (VECTOR1, VECTOR2, ... ) )
#   builds a matrix whose columns are VECTOR1, VECTOR2, ...

# Example

# Five column vectors
a_1 = np.matrix( [ [1], [2], [3] ] )
a_2 = np.matrix( [ [4], [5], [6] ] )
a_3 = np.matrix( [ [7], [8], [9] ] )
a_4 = np.matrix( [ [-1], [2], [0] ] )
a_5 = np.power( a_4, 5 )

print(a_1)
print(a_2)
print(a_3)
print(a_4)
print(a_5)


# Build a matrix A whose columns are a_1, ... ,a_5

A = np.column_stack(  ( a_1, a_2, a_3, a_4, a_5 )  )
print(A)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
[[7]
 [8]
 [9]]
[[-1]
 [ 2]
 [ 0]]
[[-1]
 [32]
 [ 0]]
[[ 1  4  7 -1 -1]
 [ 2  5  8  2 32]
 [ 3  6  9  0  0]]


In [ ]:
import numpy as np

A = np.matrix( [[1, 2], [3, -1]])
A**2

matrix([[7, 0],
        [0, 7]])

In [ ]:
A * A

matrix([[7, 0],
        [0, 7]])

In [ ]:
np.power(A, 2)

matrix([[1, 4],
        [9, 1]])